name: Primeiro Workflow

on:
  create:
    branches: 
      - feature/*
  push:
    branches:
      - feature/*

jobs:
  CI:
    runs-on: ubuntu-latest

    permissions: 
      pull-requests: write

    steps:

      - name: Baixando repositório
        uses: actions/checkout@v4

      - name: Configurando Python
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.11'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      
      - name: Instalando as dependências
        run: |
          pip install -e .
          pip install -r tests/test-requirements.txt
          pip install bandit ruff

      - name: Executando testes
        run: pytest tests

      - name: Linter
        run: ruff check

      - name: Aplicando pacote de segurança
        run: bandit -c pyproject.toml -r .

      - name: create pull request
        run: |
          current_branch=$(git branch --show-current)
          echo $current_branch
          gh pr create -B master -H $current_branch --title 'Merging' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
