name: Primeiro Workflow

on: 
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando repositório
        uses: actions/checkout@v4

      - name: Configurando Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Instalar as dependencias
        run: |
          pip install -e .
          pip install -r tests/test-requirements.txt

      - name: Executando testes
        run: pytest -s tests