name: Primeiro Workflow

on: 
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Hello World
        run: echo "Criando meu primeiro workflow"
